## Tugas
- Selesaikan soal-soal berikut dengan membuat program masing-masing soal sesuai yang ditanyakan.
- Kerjakan dengan membuat cell code baru di bawah setiap soal


1. Tentukan determinan matriks berikut:

$$\displaystyle A = \left( \begin{array}{cc}
1 & 2 \\
3 & 4
\end{array} 
\right)
$$

#### Jawab

In [1]:
import numpy as np

# Membuat matriks 2x2
M = np.array([[1, 2], [3, 4]])

# Menghitung determinan matriks
determinant = np.linalg.det(M)

print(determinant)

-2.0000000000000004


2. Tentukan invers Matriks Berikut:

$$\displaystyle B = \left( \begin{array}{cc}
10 & -22 \\
3 & 45
\end{array} 
\right)
$$

#### Jawab

In [3]:
import numpy as np

# Membuat matriks 2x2
M = np.array([[10, -22], [3, 45]])

# Menghitung invers matriks
inverse_of_M = np.linalg.inv(M)

print(inverse_of_M)

[[ 0.0872093   0.04263566]
 [-0.00581395  0.01937984]]


3. Tentukan apakah matriks berikut berkondisi buruk:
$$\displaystyle C = \left( \begin{array}{cc}
1 & 10^{-10} \\
10^{-10} & 1
\end{array} 
\right)
$$

#### Jawab

In [5]:
import numpy as np

# Membuat matriks 2x2
M = np.array([[1, 1e-10], [1e-10, 1]])

# Menghitung determinan matriks
determinant = np.linalg.det(M)

print(determinant)

1.0


In [6]:
import numpy as np

# Membuat matriks 2x2
M = np.array([[1, 1e-10], [1e-10, 1]])

# Menghitung invers matriks
inverse_of_M = np.linalg.inv(M)

print(inverse_of_M)

[[ 1.e+00 -1.e-10]
 [-1.e-10  1.e+00]]


In [ ]:
import numpy as np

# Matriks C
C = np.array([[1, 1e-10],
              [1e-10, 1]])

# Hitung nilai singular menggunakan nilai eigen
eigenvalues = np.linalg.eigvals(C)

# Hitung kondisi numerik
condition_number = np.max(eigenvalues) / np.min(eigenvalues)

print("Nilai singular (eigenvalues):", eigenvalues)
print("Kondisi numerik:", condition_number)


Matriks di atas dalam kondisi baik karena determinannya tidak sama dengan nol atau bahkan mendekati nol. Kondisi numerik (κ(C)) mendekati atau sama dengan 1, matriks C dianggap baik.

4. Tentukan apakah sistem persamaan linier berikut memiliki solusi. Jika ada, bagaimana solusinya?

$$\displaystyle A = \left( \begin{array}{cc}
1 & 2 \\
3 & 4
\end{array} 
\right) $$


$$\displaystyle
b =  \left( \begin{array}{cc}
5 & 6 
\end{array} 
\right) \\
$$

##### Jawab

In [11]:
import numpy as np

# Matriks koefisien A
A = np.array([[1, 2],
              [3, 4,]])

# Vektor kolom hasil b
b = np.array([5, 6])

# Menyelesaikan sistem persamaan linear Ax = b
x = np.linalg.solve(A, b)

# Menampilkan solusi
print("Solusi:")
print(x)


Solusi:
[-4.   4.5]


5. Tentukan dimensi ruang nol matriks berikut:


$$\displaystyle
C =
\left(
\begin{array}{ccc}
1 & 2 & 3 \\
4 & 5 & 6 \\
7 & 8 & 9
\end{array}
\right)
$$

#### Jawab

In [15]:
import numpy as np

# Matriks C
C = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

# Temukan ruang nol dengan menggunakan SVD
_, _, null_space = np.linalg.svd(C)

# Hitung dimensi ruang nol
dimension_null_space = np.sum(np.isclose(_, 0))

# Tampilkan hasil
print("Ruang Nol Matriks C:")
print(null_space)
print(f"Dimensi Ruang Nol: {dimension_null_space}")


Ruang Nol Matriks C:
[[-0.47967118 -0.57236779 -0.66506441]
 [-0.77669099 -0.07568647  0.62531805]
 [-0.40824829  0.81649658 -0.40824829]]
Dimensi Ruang Nol: 1
